name: Deploy to Railway

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: npm install
            - name: Run Migrations
              run: npx sequelize db:migrate
